"""Service-layer protocol contracts for dependency inversion."""

from __future__ import annotations

from typing import Protocol

from sqlalchemy.ext.asyncio import AsyncSession


class SyncServiceProtocol(Protocol):
    async def get_status(self, session: AsyncSession) -> dict: ...

    async def trigger_manual_sync(self, session: AsyncSession) -> dict: ...


class TaskServiceProtocol(Protocol):
    async def list_tasks(self, session: AsyncSession) -> list[dict]: ...

    async def get_task(self, session: AsyncSession, uuid: str) -> dict: ...

    async def get_task_checklist(self, session: AsyncSession, uuid: str) -> list[dict]: ...

    async def list_areas(self, session: AsyncSession) -> list[dict]: ...

    async def list_tags(self, session: AsyncSession) -> list[dict]: ...

    async def create_task(self, session: AsyncSession, **payload) -> dict: ...

    async def update_task(self, session: AsyncSession, uuid: str, updates: dict) -> dict: ...

    async def delete_task(self, session: AsyncSession, uuid: str) -> None: ...


class TaskCommandMapperProtocol(Protocol):
    def to_create_payload(self, body, *, status_enum, schedule_enum, type_enum) -> dict: ...

    def to_update_payload(self, updates: dict, *, status_enum, schedule_enum, type_enum) -> dict: ...
